FROM python:VERSION

COPY requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

COPY jupyter_notebook_config.py /root/.jupyter/jupyter_notebook_config.py

ENV DISPLAY :0
WORKDIR /project

CMD ["/bin/bash"]

